version: '2'
services:
    ng4-app:
        image: ng4
        external_links:
            - ng4-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ng4?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ng4-mysql:
        extends:
            file: mysql.yml
            service: ng4-mysql
