version: '2'
services:
    ng4-mysql:
        container_name: ng4-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/ng4/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ng4
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
